export enum Department{
    MARKETING,
    SOFTWARE_DEVELOPMENT,
    IT_OPERATIONS,
    PROJECT_MANAGEMENT,
    DATABASE_ADMINISTRATION,
    CYBERSECURITY,

    TECHNICAL_SUPPORT, 
    NETWORK_ADMINISTRATION,
    DATA_ANALYTICS,
    IT_TRAINING_AND_DOCUMENTATION,

    IT_STRATEGY_AND_PLANNING,
    IT_COMPLIANCE_AND_GOVERNANCE,
    BUSINESS_INTELLIGENCE
}